<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8f1586ab-b740-40a5-8617-eb90f9c276a6</testSuiteGuid>
   <testCaseLink>
      <guid>784afd1b-677d-4a55-9560-d717ae059c5e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8d6d121-aa97-4198-8aa7-2afb60611865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ce94fa9-7a4a-49ad-a404-52043459ebcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>228a440c-d3fa-4f31-b6fd-bca4dbe00b6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Invalid Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>712689b0-b20f-4d68-9841-dcc1f576cda2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72a36903-d8e2-4a83-b99a-98ffb8757b7b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
